directory: ~/Music

import:
  copy: yes
  write: yes
  log: beetslog.txt

art_filename: cover

match:
  preferred:
    countries: ["US", "GB|UK", "PL"]
    media: ["CD", "Digital Media|File"]
    original_year: yes

plugins: chroma deezer spotify embedart fetchart lyrics replaygain badfiles duplicates

paths:
  default: $albumartist/$album%aunique{}%ifdef{disc, (Disc $disc)}/$track - $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title
