directory: ~/Music/FLAC
library: ~/Music/library.db

import:
  copy: yes
  write: yes
  log: beetslog.txt
  languages: en pl

art_filename: cover

match:
  preferred:
    countries: ["US", "GB|UK", "PL"]
    media: ["CD", "Digital Media|File"]
    original_year: yes

plugins:
  - autobpm
  - convert
  - chroma
  - deezer
  - spotify
  - embedart
  - fetchart
  - info
  - musicbrainz
  - playlist
  - badfiles
  - duplicates
  - lyrics
  - edit
  - replaygain
  - rewrite

paths:
  default: $albumartist/$album%aunique{}%ifdef{disc, (Disc $disc)}/$track - $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

convert:
  auto: no
  copy_album_art: yes
  album_art_maxwidth: 600
  dest: ~/Music/Opus
  embed: yes
  format: opus
  formats:
    mp3:
      command: ffmpeg -i $source -y -vn -aq 0 $dest
    aac:
      command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
      extension: m4a
    opus:
      command: ffmpeg -i $source -y -vn -c:a libopus -b:a 160k $dest
      extension: ogg

replaygain:
  backend: gstreamer
