directory: ~/Music/FLAC
library: ~/Music/library.db

import:
  copy: yes
  write: yes
  resume: ask
  detail: yes
  log: beetslog.txt
  languages: en pl

art_filename: cover

match:
  preferred:
    countries: ["US", "GB|UK", "PL"]
    media: ["CD", "Digital Media|File"]
    original_year: yes

plugins:
  - autobpm
  - convert
  - chroma
  - deezer
  - spotify
  - embedart
  - fetchart
  - info
  - musicbrainz
  - playlist
  - badfiles
  - duplicates
  - lyrics
  - lastgenre
  - edit
  - replaygain
  - rewrite
  - extrafiles

paths:
  default: $albumartist/$album%aunique{}%ifdef{disc, (Disc $disc)}/$track - $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

convert:
  auto: no
  copy_album_art: yes
  album_art_maxwidth: 600
  dest: ~/Music/MP3
  embed: yes
  format: mp3
  formats:
    mp3:
      command: sh -c 'ffmpeg -i "$1" -y -vn -aq 0 "$2"; beet lyrics -lp "$1" > "${2%.*}.lrc"' -- $source $dest

replaygain:
  backend: gstreamer

autobpm:
  auto: yes

musicbrainz:
  ratelimit: 4

lyrics:
  auto: yes
  synced: yes

extrafiles:
  patterns:
    all: "*.*"
