directory: ~/Music/FLAC
library: ~/Music/library.db

import:
  copy: yes
  write: yes
  log: beetslog.txt

art_filename: cover

match:
  preferred:
    countries: ["US", "GB|UK", "PL"]
    media: ["CD", "Digital Media|File"]
    original_year: yes

plugins: convert chroma deezer spotify embedart fetchart replaygain badfiles duplicates lyrics

paths:
  default: $albumartist/$album%aunique{}%ifdef{disc, (Disc $disc)}/$track - $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

convert:
  auto: no
  copy_album_art: yes
  album_art_maxwidth: 600
  dest: ~/Music/MP3
  embed: yes
  format: mp3
  formats:
    mp3:
      command: ffmpeg -i $source -y -vn -aq 0 $dest
    aac:
      command: ffmpeg -i $source -y -vn -acodec aac -aq 1 $dest
      extension: m4a
